-- 100 Things to Do Before you Die Seed Script
-- Usage: Replace 'YOUR_USER_ID_HERE' with your actual Supabase User UUID before running.

DO $$
DECLARE
    target_user_id uuid := '59b95405-1963-476d-a6b8-5041857ee24e'; -- <--- REPLACE THIS WITH YOUR USER ID
    new_list_id uuid;
BEGIN
    -- 1. Create the Bucket List
    INSERT INTO public.bucket_lists (user_id, name, description, category, is_public, follower_count)
    VALUES (
        target_user_id,
        '100 Things to Do Before you Die',
        'The ultimate bucket list of 100 things to do before you die.',
        'miscellaneous',
        true,
        0
    )
    RETURNING id INTO new_list_id;

    -- 2. Insert the Bucket Items
    -- NOTE: 'category' column removed as it does not exist on bucket_items table
    INSERT INTO public.bucket_items (bucket_list_id, title, points, difficulty, completed)
    VALUES
        (new_list_id, 'Set foot on all continents', 10, 'hard', false),
        (new_list_id, 'Live at least in 2 different countries with completely different cultures', 10, 'hard', false),
        (new_list_id, 'Solve a Rubik''s cube', 10, 'medium', false),
        (new_list_id, 'Learn at least one foreign language', 10, 'medium', false),
        (new_list_id, 'Swim with whale sharks', 10, 'medium', false),
        (new_list_id, 'Get drunk at least once in your life', 10, 'easy', false),
        (new_list_id, 'Bungee jump', 10, 'medium', false),
        (new_list_id, 'Do the Mongol Rally', 10, 'hard', false),
        (new_list_id, 'Swim with dolphins', 10, 'medium', false),
        (new_list_id, 'Go on a Safari', 10, 'medium', false),
        (new_list_id, 'Learn how to surf', 10, 'medium', false),
        (new_list_id, 'Scuba dive', 10, 'medium', false),
        (new_list_id, 'Fly an airplane', 10, 'hard', false),
        (new_list_id, 'Give a public speech', 10, 'medium', false),
        (new_list_id, 'Get your body in the ultimate shape at least once in your life', 10, 'hard', false),
        (new_list_id, 'Run a marathon', 10, 'hard', false),
        (new_list_id, 'Run a triathlon', 10, 'hard', false),
        (new_list_id, 'Hot air ballooning', 10, 'medium', false),
        (new_list_id, 'Ride a motorcycle', 10, 'medium', false),
        (new_list_id, 'Sing to an audience (Karaoke counts)', 10, 'easy', false),
        (new_list_id, 'Volunteer 6 months abroad', 10, 'hard', false),
        (new_list_id, 'Have your own business', 10, 'hard', false),
        (new_list_id, 'Fish and eat your catch', 10, 'medium', false),
        (new_list_id, 'Own a pet', 10, 'medium', false),
        (new_list_id, 'Renew your vows', 10, 'medium', false),
        (new_list_id, 'Watch the top 10 movies of all time', 10, 'easy', false),
        (new_list_id, 'White water rapids', 10, 'medium', false),
        (new_list_id, 'Try rock climbing', 10, 'medium', false),
        (new_list_id, 'Dive into the water from a cliff', 10, 'medium', false),
        (new_list_id, 'Learn how to make Sushi', 10, 'medium', false),
        (new_list_id, 'Go to Disney World', 10, 'medium', false),
        (new_list_id, 'Learn how to sail', 10, 'medium', false),
        (new_list_id, 'Paint and frame your painting', 10, 'medium', false),
        (new_list_id, 'Help a stranger in distress', 10, 'medium', false),
        (new_list_id, 'Ride a rollercoaster', 10, 'easy', false),
        (new_list_id, 'Drive the Autobahn', 10, 'medium', false),
        (new_list_id, 'Spend Christmas on the beach', 10, 'medium', false),
        (new_list_id, 'Get your B.A. or equivalent', 10, 'hard', false),
        (new_list_id, 'Find a job you love or create the job you love', 10, 'hard', false),
        (new_list_id, 'Read the top 5 novels of all time', 10, 'medium', false),
        (new_list_id, 'Sleep under the stars', 10, 'easy', false),
        (new_list_id, 'Make a fool of yourself', 10, 'easy', false),
        (new_list_id, 'Drive across an entire country', 10, 'hard', false),
        (new_list_id, 'See a Solar Eclipse', 10, 'medium', false),
        (new_list_id, 'Spend the night in a haunted place', 10, 'medium', false),
        (new_list_id, 'Learn how to play a musical instrument', 10, 'hard', false),
        (new_list_id, 'Drink beer at the Oktoberfest', 10, 'medium', false),
        (new_list_id, 'Sleep in an igloo', 10, 'medium', false),
        (new_list_id, 'Brew your own beer', 10, 'medium', false),
        (new_list_id, 'Go to the Superbowl', 10, 'medium', false),
        (new_list_id, 'Go to the Olympics (Summer or Winter)', 10, 'medium', false),
        (new_list_id, 'Write a book (at least try)', 10, 'hard', false),
        (new_list_id, 'Plant a tree', 10, 'easy', false),
        (new_list_id, 'Learn how to dance', 10, 'medium', false),
        (new_list_id, 'Ride a camel in the desert', 10, 'medium', false),
        (new_list_id, 'Ride an elephant', 10, 'medium', false),
        (new_list_id, 'Grow a beard at least once in your life', 10, 'easy', false),
        (new_list_id, 'Shave your hair off', 10, 'easy', false),
        (new_list_id, 'Go skinny dipping', 10, 'easy', false),
        (new_list_id, 'Go to your favorite band''s concert', 10, 'medium', false),
        (new_list_id, 'Climb a mountain', 10, 'hard', false),
        (new_list_id, 'Learn how to swim', 10, 'medium', false),
        (new_list_id, 'Party until sunrise', 10, 'easy', false),
        (new_list_id, 'Go wild at La Tomatina', 10, 'medium', false),
        (new_list_id, 'Go to the Opera', 10, 'medium', false),
        (new_list_id, 'Cross a country using public transportation', 10, 'hard', false),
        (new_list_id, 'Get to know your neighbors', 10, 'easy', false),
        (new_list_id, 'Travel around the world', 10, 'hard', false),
        (new_list_id, 'Backpack through another country', 10, 'medium', false),
        (new_list_id, 'Go Camping', 10, 'easy', false),
        (new_list_id, 'Feed a homeless person', 10, 'easy', false),
        (new_list_id, 'Take a class you''ve always wanted', 10, 'medium', false),
        (new_list_id, 'Own a sportscar', 10, 'medium', false),
        (new_list_id, 'Go Skiing', 10, 'medium', false),
        (new_list_id, 'Shoot a gun', 10, 'medium', false),
        (new_list_id, 'Trek to Machu Pichu', 10, 'medium', false),
        (new_list_id, 'Visit Angkor Wat', 10, 'medium', false),
        (new_list_id, 'See the Iguazu Falls', 10, 'medium', false),
        (new_list_id, 'Go Kayaking', 10, 'medium', false),
        (new_list_id, 'Dance at the Carnival in Rio', 10, 'medium', false),
        (new_list_id, 'See a Glacier', 10, 'medium', false),
        (new_list_id, 'Take a bath in a hot spring', 10, 'easy', false),
        (new_list_id, 'Try to beat a world record', 10, 'hard', false),
        (new_list_id, 'Go to a drive-in movie theatre', 10, 'easy', false),
        (new_list_id, 'Ride a gondola in Venice', 10, 'medium', false),
        (new_list_id, 'See the Eiffel Tower', 10, 'medium', false),
        (new_list_id, 'Fly a kite', 10, 'easy', false),
        (new_list_id, 'Solve a Jigsaw puzzle', 10, 'easy', false),
        (new_list_id, 'Be an extra in a movie', 10, 'medium', false),
        (new_list_id, 'Dance the Macarena', 10, 'easy', false),
        (new_list_id, 'Eat Fried Oreos / Twinkies / Cheescake', 10, 'easy', false),
        (new_list_id, 'Float in the Dead Sea', 10, 'medium', false),
        (new_list_id, 'Travel at least once by train', 10, 'easy', false),
        (new_list_id, 'Go on a cruise', 10, 'medium', false),
        (new_list_id, 'See the Northern Lights (Aurora Borealis)', 10, 'medium', false),
        (new_list_id, 'Travel by yourself', 10, 'medium', false),
        (new_list_id, 'Ride a horse', 10, 'medium', false),
        (new_list_id, 'Fall in love', 10, 'medium', false),
        (new_list_id, 'Learn how to juggle', 10, 'medium', false),
        (new_list_id, 'Feel like the happiest person on Earth', 10, 'hard', false);

END $$;
